linters:
  enable:
    - gofmt
    - govet

issues:
  exclude-dirs:
    - pkg/proto
    - internal/gen

  exclude-rules:
    - path: '.*\.pb\.go$'
      linters:
        - govet
        - gofmt
    - path: '.*_grpc\.pb\.go$'
      linters:
        - govet
        - gofmt