linters:
  enable:
    - gofmt
    - govet

issues:
  # Новый формат исключения директорий (вместо устаревшего run.skip-dirs)
  exclude-dirs:
    - pkg/proto  

  exclude-rules:
    - path: '.*\.pb\.go$'
    - path: '.*_grpc\.pb\.go$' 